### ISSUE TITLE
1.0.0.Alpha

### ISSUE THREAD

**Issue by Kloen** [Kloen/citra-android#41]
## CURRENT PROGRESS STOPPED BY PRIORITY WORK ON OTHER PROJECTS
- [ ] Finish all related issues
- [ ] Publish on Google Play

**Comment by justynpryce** [comment]
Hi, I installed your Citra Android port but unfortunately it is in a .zip file and I am not sure how to transfer from .zip to .apk on android, I don't have a computer handy and my phonemail won't root. And if you can can you give me a .apk download link. Thank you.

**Comment by Kloen** [comment]
@justynpryce 

Hi, I'm sorry, but there is no working neither final version yet, and you can't expect it soon. 

I'm busy with other projects that are more important than this one to me.

In addition, once I get back to this, and if I can finish it, you will need an Android N (7.0) device in order to be able to use this unofficial port. Note that Android N is expected to be released later this year.

Kind regards.

Also, for future questions, if have. Mail me to kloen@outlawkiwi.com. This is an issue tracker, not a support forum. Thanks.

**Comment by justynpryce** [comment]
Ok, thanks.
