### ISSUE TITLE
Update all CI to use the same Android Build Tools

### ISSUE THREAD

**Issue by Kloen** [Kloen/citra-android#60]
^that.

**Comment by DouglasCost** [comment]
How to compile apk?

**Comment by Kloen** [comment]
@DouglasCost Currently, the only way to generate an APK it's with the Android Studio itself. I have planed to generate one automatically, but I'm not going to increase CI build time by 1h without a reason, and currently, the entire app isn't even usable at any rate. Eventually I'll be adding it, and publishing it automatically to Google Play. But not anytime soon.
