### ISSUE TITLE
cant open apk

### ISSUE THREAD

**Issue by caspervanneck** [Kloen/citra-android#66]
i cant see apk when instalt and open do somting rong with building

**Comment by Kloen** [comment]
Which steps did you follow to build it?
Which OS do you have?
Which Android device are you testing with?

Actually you shouldn't expect the apk to anything but show you dummy information. All the code from Citra isn't ported or even compiled just yet, and all the code that it's on the APK at the moment it's quite old, and, in fact, it's only the old LOGGER that they currently plan to change soon. So there is no real use in expect the port to work. If you only want to use it, simply, wait.

**Comment by caspervanneck** [comment]
are ther staps @Kloen and my android version 7.0 my device samsung galexy s6

**Comment by Kloen** [comment]
The device it's fine. I don't have it to test against it, but should work.

There are steps to do it, a lot of them, and just to compile the .apk you need a least 6GB of HardDrive space to download all the required tools and code. Only the repository and it's dependencies are this big:
![image](https://cloud.githubusercontent.com/assets/9112818/26755067/3dcec72e-4886-11e7-99e2-1b1031601660.png)

My point is, if you don't plan to develop it. And you just want to use it.

There is no real point in compiling it now. It wont work as you want it to. It wont load games, not even read a list of games, and if you expect it to show you a fancy triangle, well, it doesn't do it anymore.

**Comment by caspervanneck** [comment]
okey

**Comment by caspervanneck** [comment]
any fixses for that soon or need i just wait for a fix

**Comment by Kloen** [comment]
It's not a fix, because it isn't a bug either.

It just takes a lot of time and effort to make things work properly. I don't have a real stop to keep working on it, but it takes time to do it. Only thing you can do if you want to use it, is wait. I'll try to keep this repository updated, and eventually, start to publish an .apk, but as I said. It will take some time.

**Comment by caspervanneck** [comment]
okey tank you for your time @Kloen
