### ISSUE TITLE
CI: Generate .apk

### ISSUE THREAD

**Issue by Kloen** [Kloen/citra-android#7]
Add a way to generate the .apk and store it somewhere.

**Comment by Kloen** [comment]
It requires a keystore.

Somehow, it's not working properly with current gradle-experimental. Didn't dig any further.

**Comment by BenNottelling** [comment]
How do you generate the .apk?

**Comment by Kloen** [comment]
@BenNottelling For debug purposes it can be generated only with Android Studio, like any other Android Application.

For release purposes, the one that are targeted in this issue, you also require a keystore, in this case, it will be stored on CircleCI / Travis / AppVeyor, to compile 3 .apk of the application, and release it on GitHub Releases.

As I said, I didn't dig any further in this topic, cause it's not prioritary at all to generate an .apk, when the code itself doesn't even work. Cause well, if you look to other issues here, there is a lot of things that remain unimplemented.
